### PR TITLE
[FIX] Catch illegal argument exception

### PR DESCRIPTION
**Pull request by adgeg**
To avoid recurrent IllegalArgumentException, as mentioned in https://github.com/Diolor/Swipecards/issues/24, this branch implements the solution provided by @wtttc.

### CODE REVIEW

**Comment by Diolor** [comment]
Thanks for this @adgeg. Will merge this as soon as I will find some additional time to upload it to the repo.

**Comment by younes0** [comment]
@adgeg How can I include your lib version?

**Comment by younes0** [comment]
@Diolor could you help me on this one?

**Comment by jainrocks** [comment]
@adgeg  How to use this modification, @Diolor  please update the library...

**Comment by RadicalMonkey** [comment]
@Diolor Do you know if you'll be able to merge this PR and release a new version? I'm getting a number of crashes due to this particular issue.

Thanks

**Pull request merged**
