### PR TITLE
Added ability to accept input events on children.

### PR DESCRIPTION
**Pull request by Nidre**
Added ability to accept input events on children. See issue: https://github.com/Diolor/Swipecards/issues/68

### CODE REVIEW

**Comment by hy9be** [comment]
@Diolor could you take a look at this PR? I believe @Nidre @lushan1314 and myself are not the only ones need this. Thanks!

**Comment by hy9be** [comment]
@Nidre I suggest you only include commit 05921101b4d51c9d7fbb54eaec4608e1d8b5be30 in this PR. The new features in a1482ce2b2bc32f4e2089ad1cc2a0ec7cf9f5eb3 is somewhat aggressive.

**Comment by Nidre** [comment]
@hy9be My bad I thought I was only sending the first one. Gonna Cherry Pick and send the relevant one soon.

**Comment by Nidre** [comment]
@Diolor  @hy9be  See: https://github.com/Diolor/Swipecards/pull/91

**Comment by hy9be** [comment]
I tried it yesterday and find some problems with this change. The line 264 https://github.com/Nidre/Swipecards/commit/05921101b4d51c9d7fbb54eaec4608e1d8b5be30#diff-75ba04a674fd52a4f22f21b17c4bd404R264 call ``setOnTouchListener``. That conflicts with the default ``onTouchListener`` for some views, e.g. ``ListView`` will not be able to be scrolled.

**Comment by Nidre** [comment]
@hy9be Interesting. I haven't really checked this anything other than CardView, FrameLayout, LinearLayout and RelativeLayout. Not sure how it would work with ListView since it sets a touch listener.

If you could send me an example project I would be happy to try it out.

**Comment by hy9be** [comment]
Yes. I did (b) and it works. So I guess your changes could work as a hack to support events on child views. But may not be that ideal to become a part of the library itself. IMHO.

**Comment by Nidre** [comment]
@hy9be Well I wouldn't say hack. Because it doesn't do anything different than the library itself. It depends on your needs. My solutions simply says direct all touch events in all children to FlingListener. But if that is not your need, it seems not, you would need another solution. I am not sure if there is a nice way of doing that except adding or removing listener manually.

**Comment by hy9be** [comment]
Agree.

**Pull request closed without merging**
